# /opt/bin/nginx -c /code/nginx.conf -g 'daemon off;'

events { worker_connections 1024; }
http {
    limit_conn_zone $binary_remote_addr zone=one:10m;
    limit_conn_status 429;

    server {
        
        error_log  /dev/stderr;
        access_log /dev/stdout;
            

        gzip on;
        gzip_min_length 1k;
        gzip_comp_level 2;
        gzip_types text/html text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png image/svg+xml;
        gzip_vary on;
        gzip_disable "MSIE [1-6]\.";
        include /opt/nginx/conf/mime.types;
        add_header Access-Control-Allow-Origin *;

        listen 9000;

        limit_rate 200k;
        limit_conn one 2;


        location / {
            root /code;
            index index.html;
            try_files $uri $uri/ /index.html;
            # if ( !-e $request_filename ) {
            #     rewrite ^/(.*) https://blog.seiki.fun/$1 permanent;
                
            # }
        }

        # location ~ ^/.(images|javascript|js|css|flash|media|static)/ {
        #      root /code;       
        # }

    }
}